import Decimal from "./break_infinity.js";

const bonds = {
    "sample": {
        name: "",
        elements: {}
    },
    "H2O": {
        name: "Water",
        elements: {
            "H": 2,
            "O": 1,
        }
    },
    "CO2": {
        name: "Carbon Dioxide",
        elements: {
            "C": 1,
            "O": 2,
        }
    },
    "H2": {
        name: "Deuterium",
        elements: {
            "H": 2,
        }
    },
    "H2O2": {
        name: "Hydrogen Peroxide",
        elements: {
            "H": 2,
            "O": 2,
        }
    },
    "H3": {
        name: "Tritium",
        elements: {
            "H": 3,
        }
    },
    "He2": {
        name: "Helium Molecule",
        elements: {
            "He": 2,
        }
    },
    "": {

    }
}

const elements = {
    "H": { name: "Hydrogen", atomic_num: 1, atomic_weight: 1.008 },
    "He": { name: "Helium", atomic_num: 2, atomic_weight: 4.0026 },
    "Li": { name: "Lithium", atomic_num: 3, atomic_weight: 6.94 },
    "Be": { name: "Beryllium", atomic_num: 4, atomic_weight: 9.0122 },
    "B": { name: "Boron", atomic_num: 5, atomic_weight: 10.81 },
    "C": { name: "Carbon", atomic_num: 6, atomic_weight: 12.011 },
    "N": { name: "Nitrogen", atomic_num: 7, atomic_weight: 14.007 },
    "O": { name: "Oxygen", atomic_num: 8, atomic_weight: 15.999 },
    "F": { name: "Fluorine", atomic_num: 9, atomic_weight: 18.998 },
    "Ne": { name: "Neon", atomic_num: 10, atomic_weight: 20.180 },
    "Na": { name: "Sodium", atomic_num: 11, atomic_weight: 22.990 },
    "Mg": { name: "Magnesium", atomic_num: 12, atomic_weight: 24.305 },
    "Al": { name: "Aluminum", atomic_num: 13, atomic_weight: 26.982 },
    "Si": { name: "Silicon", atomic_num: 14, atomic_weight: 28.085 },
    "P": { name: "Phosphorus", atomic_num: 15, atomic_weight: 30.974 },
    "S": { name: "Sulfur", atomic_num: 16, atomic_weight: 32.06 },
    "Cl": { name: "Chlorine", atomic_num: 17, atomic_weight: 35.45 },
    "Ar": { name: "Argon", atomic_num: 18, atomic_weight: 39.948 },
    "K": { name: "Potassium", atomic_num: 19, atomic_weight: 39.098 },
    "Ca": { name: "Calcium", atomic_num: 20, atomic_weight: 40.078 },
    "Sc": { name: "Scandium", atomic_num: 21, atomic_weight: 44.956 },
    "Ti": { name: "Titanium", atomic_num: 22, atomic_weight: 47.867 },
    "V": { name: "Vanadium", atomic_num: 23, atomic_weight: 50.942 },
    "Cr": { name: "Chromium", atomic_num: 24, atomic_weight: 51.996 },
    "Mn": { name: "Manganese", atomic_num: 25, atomic_weight: 54.938 },
    "Fe": { name: "Iron", atomic_num: 26, atomic_weight: 55.845 },
    "Co": { name: "Cobalt", atomic_num: 27, atomic_weight: 58.933 },
    "Ni": { name: "Nickel", atomic_num: 28, atomic_weight: 58.693 },
    "Cu": { name: "Copper", atomic_num: 29, atomic_weight: 63.546 },
    "Zn": { name: "Zinc", atomic_num: 30, atomic_weight: 65.38 },
    "Ga": { name: "Gallium", atomic_num: 31, atomic_weight: 69.723 },
    "Ge": { name: "Germanium", atomic_num: 32, atomic_weight: 72.63 },
    "As": { name: "Arsenic", atomic_num: 33, atomic_weight: 74.922 },
    "Se": { name: "Selenium", atomic_num: 34, atomic_weight: 78.96 },
    "Br": { name: "Bromine", atomic_num: 35, atomic_weight: 79.904 },
    "Kr": { name: "Krypton", atomic_num: 36, atomic_weight: 83.798 },
    "Rb": { name: "Rubidium", atomic_num: 37, atomic_weight: 85.468 },
    "Sr": { name: "Strontium", atomic_num: 38, atomic_weight: 87.62 },
    "Y": { name: "Yttrium", atomic_num: 39, atomic_weight: 88.906 },
    "Zr": { name: "Zirconium", atomic_num: 40, atomic_weight: 91.224 },
    "Nb": { name: "Niobium", atomic_num: 41, atomic_weight: 92.906 },
    "Mo": { name: "Molybdenum", atomic_num: 42, atomic_weight: 95.95 },
    "Tc": { name: "Technetium", atomic_num: 43, atomic_weight: 98 },
    "Ru": { name: "Ruthenium", atomic_num: 44, atomic_weight: 101.07 },
    "Rh": { name: "Rhodium", atomic_num: 45, atomic_weight: 102.91 },
    "Pd": { name: "Palladium", atomic_num: 46, atomic_weight: 106.42 },
    "Ag": { name: "Silver", atomic_num: 47, atomic_weight: 107.87 },
    "Cd": { name: "Cadmium", atomic_num: 48, atomic_weight: 112.41 },
    "In": { name: "Indium", atomic_num: 49, atomic_weight: 114.82 },
    "Sn": { name: "Tin", atomic_num: 50, atomic_weight: 118.71 },
    "Sb": { name: "Antimony", atomic_num: 51, atomic_weight: 121.76 },
    "Te": { name: "Tellurium", atomic_num: 52, atomic_weight: 127.6 },
    "I": { name: "Iodine", atomic_num: 53, atomic_weight: 126.90 },
    "Xe": { name: "Xenon", atomic_num: 54, atomic_weight: 131.29 },
    "Cs": { name: "Cesium", atomic_num: 55, atomic_weight: 132.91 },
    "Ba": { name: "Barium", atomic_num: 56, atomic_weight: 137.33 },
    "La": { name: "Lanthanum", atomic_num: 57, atomic_weight: 138.91 },
    "Ce": { name: "Cerium", atomic_num: 58, atomic_weight: 140.12 },
    "Pr": { name: "Praseodymium", atomic_num: 59, atomic_weight: 140.91 },
    "Nd": { name: "Neodymium", atomic_num: 60, atomic_weight: 144.24 },
    "Pm": { name: "Promethium", atomic_num: 61, atomic_weight: 145 },
    "Sm": { name: "Samarium", atomic_num: 62, atomic_weight: 150.36 },
    "Eu": { name: "Europium", atomic_num: 63, atomic_weight: 151.96 },
    "Gd": { name: "Gadolinium", atomic_num: 64, atomic_weight: 157.25 },
    "Tb": { name: "Terbium", atomic_num: 65, atomic_weight: 158.93 },
    "Dy": { name: "Dysprosium", atomic_num: 66, atomic_weight: 162.50 },
    "Ho": { name: "Holmium", atomic_num: 67, atomic_weight: 164.93 },
    "Er": { name: "Erbium", atomic_num: 68, atomic_weight: 167.26 },
    "Tm": { name: "Thulium", atomic_num: 69, atomic_weight: 168.93 },
    "Yb": { name: "Ytterbium", atomic_num: 70, atomic_weight: 173.05 },
    "Lu": { name: "Lutetium", atomic_num: 71, atomic_weight: 174.97 },
    "Hf": { name: "Hafnium", atomic_num: 72, atomic_weight: 178.49 },
    "Ta": { name: "Tantalum", atomic_num: 73, atomic_weight: 180.95 },
    "W": { name: "Tungsten", atomic_num: 74, atomic_weight: 183.84 },
    "Re": { name: "Rhenium", atomic_num: 75, atomic_weight: 186.21 },
    "Os": { name: "Osmium", atomic_num: 76, atomic_weight: 190.23 },
    "Ir": { name: "Iridium", atomic_num: 77, atomic_weight: 192.22 },
    "Pt": { name: "Platinum", atomic_num: 78, atomic_weight: 195.08 },
    "Au": { name: "Gold", atomic_num: 79, atomic_weight: 196.97 },
    "Hg": { name: "Mercury", atomic_num: 80, atomic_weight: 200.59 },
    "Tl": { name: "Thallium", atomic_num: 81, atomic_weight: 204.38 },
    "Pb": { name: "Lead", atomic_num: 82, atomic_weight: 207.2 },
    "Bi": { name: "Bismuth", atomic_num: 83, atomic_weight: 208.98 },
    "Po": { name: "Polonium", atomic_num: 84, atomic_weight: 209 },
    "At": { name: "Astatine", atomic_num: 85, atomic_weight: 210 },
    "Rn": { name: "Radon", atomic_num: 86, atomic_weight: 222 },
    "Fr": { name: "Francium", atomic_num: 87, atomic_weight: 223 },
    "Ra": { name: "Radium", atomic_num: 88, atomic_weight: 226 },
    "Ac": { name: "Actinium", atomic_num: 89, atomic_weight: 227 },
    "Th": { name: "Thorium", atomic_num: 90, atomic_weight: 232.04 },
    "Pa": { name: "Protactinium", atomic_num: 91, atomic_weight: 231.04 },
    "U": { name: "Uranium", atomic_num: 92, atomic_weight: 238.03 },
    "Np": { name: "Neptunium", atomic_num: 93, atomic_weight: 237 },
    "Pu": { name: "Plutonium", atomic_num: 94, atomic_weight: 244 },
    "Am": { name: "Americium", atomic_num: 95, atomic_weight: 243 },
    "Cm": { name: "Curium", atomic_num: 96, atomic_weight: 247 },
    "Bk": { name: "Berkelium", atomic_num: 97, atomic_weight: 247 },
    "Cf": { name: "Californium", atomic_num: 98, atomic_weight: 251 },
    "Es": { name: "Einsteinium", atomic_num: 99, atomic_weight: 252 },
    "Fm": { name: "Fermium", atomic_num: 100, atomic_weight: 257 },
    "Md": { name: "Mendelevium", atomic_num: 101, atomic_weight: 258 },
    "No": { name: "Nobelium", atomic_num: 102, atomic_weight: 259 },
    "Lr": { name: "Lawrencium", atomic_num: 103, atomic_weight: 262 },
    "Rf": { name: "Rutherfordium", atomic_num: 104, atomic_weight: 267 },
    "Db": { name: "Dubnium", atomic_num: 105, atomic_weight: 270 },
    "Sg": { name: "Seaborgium", atomic_num: 106, atomic_weight: 271 },
    "Bh": { name: "Bohrium", atomic_num: 107, atomic_weight: 270 },
    "Hs": { name: "Hassium", atomic_num: 108, atomic_weight: 277 },
    "Mt": { name: "Meitnerium", atomic_num: 109, atomic_weight: 278 },
    "Ds": { name: "Darmstadtium", atomic_num: 110, atomic_weight: 281 },
    "Rg": { name: "Roentgenium", atomic_num: 111, atomic_weight: 282 },
    "Cn": { name: "Copernicium", atomic_num: 112, atomic_weight: 285 },
    "Nh": { name: "Nihonium", atomic_num: 113, atomic_weight: 286 },
    "Fl": { name: "Flerovium", atomic_num: 114, atomic_weight: 289 },
    "Mc": { name: "Moscovium", atomic_num: 115, atomic_weight: 290 },
    "Lv": { name: "Livermorium", atomic_num: 116, atomic_weight: 293 },
    "Ts": { name: "Tennessine", atomic_num: 117, atomic_weight: 294 },
    "Og": { name: "Oganesson", atomic_num: 118, atomic_weight: 294 }
};

const baseElements = {
    "H": { count: new Decimal(100), unlocked: true },
    "He": { count: new Decimal(0), unlocked: false },
    "Li": { count: new Decimal(0), unlocked: false },
    "Be": { count: new Decimal(0), unlocked: false },
    "B": { count: new Decimal(0), unlocked: false },
    "C": { count: new Decimal(0), unlocked: false },
    "N": { count: new Decimal(0), unlocked: false },
    "O": { count: new Decimal(0), unlocked: false },
    "F": { count: new Decimal(0), unlocked: false },
    "Ne": { count: new Decimal(0), unlocked: false },
    "Na": { count: new Decimal(0), unlocked: false },
    "Mg": { count: new Decimal(0), unlocked: false },
    "Al": { count: new Decimal(0), unlocked: false },
    "Si": { count: new Decimal(0), unlocked: false },
    "P": { count: new Decimal(0), unlocked: false },
    "S": { count: new Decimal(0), unlocked: false },
    "Cl": { count: new Decimal(0), unlocked: false },
    "Ar": { count: new Decimal(0), unlocked: false },
    "K": { count: new Decimal(0), unlocked: false },
    "Ca": { count: new Decimal(0), unlocked: false },
    "Sc": { count: new Decimal(0), unlocked: false },
    "Ti": { count: new Decimal(0), unlocked: false },
    "V": { count: new Decimal(0), unlocked: false },
    "Cr": { count: new Decimal(0), unlocked: false },
    "Mn": { count: new Decimal(0), unlocked: false },
    "Fe": { count: new Decimal(0), unlocked: false },
    "Co": { count: new Decimal(0), unlocked: false },
    "Ni": { count: new Decimal(0), unlocked: false },
    "Cu": { count: new Decimal(0), unlocked: false },
    "Zn": { count: new Decimal(0), unlocked: false },
    "Ga": { count: new Decimal(0), unlocked: false },
    "Ge": { count: new Decimal(0), unlocked: false },
    "As": { count: new Decimal(0), unlocked: false },
    "Se": { count: new Decimal(0), unlocked: false },
    "Br": { count: new Decimal(0), unlocked: false },
    "Kr": { count: new Decimal(0), unlocked: false },
    "Rb": { count: new Decimal(0), unlocked: false },
    "Sr": { count: new Decimal(0), unlocked: false },
    "Y": { count: new Decimal(0), unlocked: false },
    "Zr": { count: new Decimal(0), unlocked: false },
    "Nb": { count: new Decimal(0), unlocked: false },
    "Mo": { count: new Decimal(0), unlocked: false },
    "Tc": { count: new Decimal(0), unlocked: false },
    "Ru": { count: new Decimal(0), unlocked: false },
    "Rh": { count: new Decimal(0), unlocked: false },
    "Pd": { count: new Decimal(0), unlocked: false },
    "Ag": { count: new Decimal(0), unlocked: false },
    "Cd": { count: new Decimal(0), unlocked: false },
    "In": { count: new Decimal(0), unlocked: false },
    "Sn": { count: new Decimal(0), unlocked: false },
    "Sb": { count: new Decimal(0), unlocked: false },
    "Te": { count: new Decimal(0), unlocked: false },
    "I": { count: new Decimal(0), unlocked: false },
    "Xe": { count: new Decimal(0), unlocked: false },
    "Cs": { count: new Decimal(0), unlocked: false },
    "Ba": { count: new Decimal(0), unlocked: false },
    "La": { count: new Decimal(0), unlocked: false },
    "Ce": { count: new Decimal(0), unlocked: false },
    "Pr": { count: new Decimal(0), unlocked: false },
    "Nd": { count: new Decimal(0), unlocked: false },
    "Pm": { count: new Decimal(0), unlocked: false },
    "Sm": { count: new Decimal(0), unlocked: false },
    "Eu": { count: new Decimal(0), unlocked: false },
    "Gd": { count: new Decimal(0), unlocked: false },
    "Tb": { count: new Decimal(0), unlocked: false },
    "Dy": { count: new Decimal(0), unlocked: false },
    "Ho": { count: new Decimal(0), unlocked: false },
    "Er": { count: new Decimal(0), unlocked: false },
    "Tm": { count: new Decimal(0), unlocked: false },
    "Yb": { count: new Decimal(0), unlocked: false },
    "Lu": { count: new Decimal(0), unlocked: false },
    "Hf": { count: new Decimal(0), unlocked: false },
    "Ta": { count: new Decimal(0), unlocked: false },
    "W": { count: new Decimal(0), unlocked: false },
    "Re": { count: new Decimal(0), unlocked: false },
    "Os": { count: new Decimal(0), unlocked: false },
    "Ir": { count: new Decimal(0), unlocked: false },
    "Pt": { count: new Decimal(0), unlocked: false },
    "Au": { count: new Decimal(0), unlocked: false },
    "Hg": { count: new Decimal(0), unlocked: false },
    "Tl": { count: new Decimal(0), unlocked: false },
    "Pb": { count: new Decimal(0), unlocked: false },
    "Bi": { count: new Decimal(0), unlocked: false },
    "Po": { count: new Decimal(0), unlocked: false },
    "At": { count: new Decimal(0), unlocked: false },
    "Rn": { count: new Decimal(0), unlocked: false },
    "Fr": { count: new Decimal(0), unlocked: false },
    "Ra": { count: new Decimal(0), unlocked: false },
    "Ac": { count: new Decimal(0), unlocked: false },
    "Th": { count: new Decimal(0), unlocked: false },
    "Pa": { count: new Decimal(0), unlocked: false },
    "U": { count: new Decimal(0), unlocked: false },
    "Np": { count: new Decimal(0), unlocked: false },
    "Pu": { count: new Decimal(0), unlocked: false },
    "Am": { count: new Decimal(0), unlocked: false },
    "Cm": { count: new Decimal(0), unlocked: false },
    "Bk": { count: new Decimal(0), unlocked: false },
    "Cf": { count: new Decimal(0), unlocked: false },
    "Es": { count: new Decimal(0), unlocked: false },
    "Fm": { count: new Decimal(0), unlocked: false },
    "Md": { count: new Decimal(0), unlocked: false },
    "No": { count: new Decimal(0), unlocked: false },
    "Lr": { count: new Decimal(0), unlocked: false },
    "Rf": { count: new Decimal(0), unlocked: false },
    "Db": { count: new Decimal(0), unlocked: false },
    "Sg": { count: new Decimal(0), unlocked: false },
    "Bh": { count: new Decimal(0), unlocked: false },
    "Hs": { count: new Decimal(0), unlocked: false },
    "Mt": { count: new Decimal(0), unlocked: false },
    "Ds": { count: new Decimal(0), unlocked: false },
    "Rg": { count: new Decimal(0), unlocked: false },
    "Cn": { count: new Decimal(0), unlocked: false },
    "Nh": { count: new Decimal(0), unlocked: false },
    "Fl": { count: new Decimal(0), unlocked: false },
    "Mc": { count: new Decimal(0), unlocked: false },
    "Lv": { count: new Decimal(0), unlocked: false },
    "Ts": { count: new Decimal(0), unlocked: false },
    "Og": { count: new Decimal(0), unlocked: false },   
}

const requirements = {
    "H": {},
    "He": { "energy": new Decimal(100), "H": new Decimal(100) },
    "Li": { "energy": new Decimal(250), "H2": new Decimal(50), "CO2": new Decimal(100)},
    "Be": { "energy": new Decimal(1000) },
    "B": { "energy": new Decimal(5000) },
    "C": { "energy": new Decimal(10000) },
    "N": { "energy": new Decimal(50000) },
    "O": { "energy": new Decimal(100000) },
    "F": { "energy": new Decimal(500000) },
    "Ne": { "energy": new Decimal(1e6) },
    "Na": { "energy": new Decimal(5e6) },
    "Mg": { "energy": new Decimal(1e7) },
    "Al": { "energy": new Decimal(1e7) },
    "Si": { "energy": new Decimal(1e8) },
    "P": { "energy": new Decimal(1e8) },
    "S": { "energy": new Decimal(1e9) },
    "Cl": { "energy": new Decimal(1e9) },
    "Ar": { "energy": new Decimal(1e10) },
    "K": { "energy": new Decimal(1e10) },
    "Ca": { "energy": new Decimal(1e11) },
    "Sc": { "energy": new Decimal(1e11) },
    "Ti": { "energy": new Decimal(1e12) },
    "V": { "energy": new Decimal(1e12) },
    "Cr": { "energy": new Decimal(1e13) },
    "Mn": { "energy": new Decimal(1e13) },
    "Fe": { "energy": new Decimal(1e14) },
    "Co": { "energy": new Decimal(1e14) },
    "Ni": { "energy": new Decimal(1e15) },
    "Cu": { "energy": new Decimal(1e15) },
    "Zn": { "energy": new Decimal(1e7) },
    "Ga": { "energy": new Decimal(1e7) },
    "Ge": { "energy": new Decimal(1e7) },
    "As": { "energy": new Decimal(1e7) },
    "Se": { "energy": new Decimal(1e7) },
    "Br": { "energy": new Decimal(1e7) },
    "Kr": { "energy": new Decimal(1e7) },
    "Rb": { "energy": new Decimal(1e7) },
    "Sr": { "energy": new Decimal(1e7) },
    "Y": { "energy": new Decimal(1e7) },
    "Zr": { "energy": new Decimal(1e7) },
    "Nb": { "energy": new Decimal(1e7) },
    "Mo": { "energy": new Decimal(1e7) },
    "Tc": { "energy": new Decimal(1e7) },
    "Ru": { "energy": new Decimal(1e7) },
    "Rh": { "energy": new Decimal(1e7) },
    "Pd": { "energy": new Decimal(1e7) },
    "Ag": { "energy": new Decimal(1e7) },
    "Cd": { "energy": new Decimal(1e7) },
    "In": { "energy": new Decimal(1e7) },
    "Sn": { "energy": new Decimal(1e7) },
    "Sb": { "energy": new Decimal(1e7) },
    "Te": { "energy": new Decimal(1e7) },
    "I": { "energy": new Decimal(1e7) },
    "Xe": { "energy": new Decimal(1e7) },
    "Cs": { "energy": new Decimal(1e7) },
    "Ba": { "energy": new Decimal(1e7) },
    "La": { "energy": new Decimal(1e7) },
    "Ce": { "energy": new Decimal(1e7) },
    "Pr": { "energy": new Decimal(1e7) },
    "Nd": { "energy": new Decimal(1e7) },
    "Pm": { "energy": new Decimal(1e7) },
    "Sm": { "energy": new Decimal(1e7) },
    "Eu": { "energy": new Decimal(1e7) },
    "Gd": { "energy": new Decimal(1e7) },
    "Tb": { "energy": new Decimal(1e7) },
    "Dy": { "energy": new Decimal(1e7) },
    "Ho": { "energy": new Decimal(1e7) },
    "Er": { "energy": new Decimal(1e7) },
    "Tm": { "energy": new Decimal(1e7) },
    "Yb": { "energy": new Decimal(1e7) },
    "Lu": { "energy": new Decimal(1e7) },
    "Hf": { "energy": new Decimal(1e7) },
    "Ta": { "energy": new Decimal(1e7) },
    "W": { "energy": new Decimal(1e7) },
    "Re": { "energy": new Decimal(1e7) },
    "Os": { "energy": new Decimal(1e7) },
    "Ir": { "energy": new Decimal(1e7) },
    "Pt": { "energy": new Decimal(1e7) },
    "Au": { "energy": new Decimal(1e7) },
    "Tl": { "energy": new Decimal(1e7) },
    "pb": { "energy": new Decimal(1e7) },
    "Bi": { "energy": new Decimal(1e7) },
    "Po": { "energy": new Decimal(1e7) },
    "At": { "energy": new Decimal(1e7) },
    "Rn": { "energy": new Decimal(1e7) },
    "Fr": { "energy": new Decimal(1e7) },
    "Ra": { "energy": new Decimal(1e7) },
    "Ac": { "energy": new Decimal(1e7) },
    "Th": { "energy": new Decimal(1e7) },
    "Pa": { "energy": new Decimal(1e7) },
    "U": { "energy": new Decimal(1e7) },
    "Np": { "energy": new Decimal(1e7) },
    "Pu": { "energy": new Decimal(1e7) },
    "Am": { "energy": new Decimal(1e7) },
    "Cm": { "energy": new Decimal(1e7) },
    "Bk": { "energy": new Decimal(1e7) },
    "Cf": { "energy": new Decimal(1e7) },
    "Es": { "energy": new Decimal(1e7) },
    "Fm": { "energy": new Decimal(1e7) },
    "Md": { "energy": new Decimal(1e7) },
    "No": { "energy": new Decimal(1e7) },
    "Lr": { "energy": new Decimal(1e7) },
    "Rf": { "energy": new Decimal(1e7) },
    "Db": { "energy": new Decimal(1e7) },
    "Sg": { "energy": new Decimal(1e7) },
    "Bh": { "energy": new Decimal(1e7) },
    "Hs": { "energy": new Decimal(1e7) },
    "Mt": { "energy": new Decimal(1e7) },
    "Ds": { "energy": new Decimal(1e7) },
    "Rg": { "energy": new Decimal(1e7) },
    "Cn": { "energy": new Decimal(1e7) },
    "Nh": { "energy": new Decimal(1e7) },
    "Fl": { "energy": new Decimal(1e7) },
    "Mc": { "energy": new Decimal(1e7) },
    "Lv": { "energy": new Decimal(1e7) },
    "Ts": { "energy": new Decimal(1e7) },
    "Og": { "energy": new Decimal(1e7) },
}

export { bonds, elements, baseElements, requirements}